#app:
#  mysql-host: localhost
#  mysql-dbname: rtb4free
#  mysql-user: ben
#  mysql-password: test
#  es-agg-url: http://192.168.2.102:9200
#  es-agg-index-campaigns: bidagg



spring:
  datasource:
    url: jdbc:mysql://34.97.103.138:3306/rtb4free
    username: c1x_user
    password: c1x_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

app:
  es-agg-url: http://192.168.2.102:9200
  es-agg-index-campaigns: bidagg
